FROM python:3.11-bullseye

WORKDIR /project

ADD ./.pre-commit-config.yaml /project/

RUN apt-get -y update && \
    apt-get -y install git && \
    git init && \
    pip install pre-commit==3.2 && \
    pre-commit install --install-hooks

RUN git config --global --add safe.directory /project
