# Generated by Django 4.2 on 2023-05-30 13:00

from django.db import migrations


def forwards(apps, schema_editor):
    VideoEncoding = apps.get_model("entities", "VideoEncoding")
    InformationFilter = apps.get_model("entities", "InformationFilter")
    ComparisonFilter = apps.get_model("entities", "ComparisonFilter")

    VideoEncoding.objects.get_or_create(
        name="AV1 - CRF30",
        ffmpeg_args=["-c:v", "libsvtav1", "-crf", "30"],
        video_extension="mkv",
    )
    VideoEncoding.objects.get_or_create(
        name="HEVC - CRF30",
        ffmpeg_args=["-c:v", "libx265", "-crf", "30"],
        video_extension="mkv",
    )

    InformationFilter.objects.get_or_create(
        name="SITI",
        ffmpeg_args=["-vf", "siti=print_summary=1"],
    )

    ComparisonFilter.objects.get_or_create(
        name="PSNR",
        ffmpeg_args=["-filter_complex", "psnr"],
    )

    ComparisonFilter.objects.get_or_create(
        name="VMAF",
        ffmpeg_args=["-lavfi", "libvmaf"],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
