# Generated by Django 4.2 on 2023-07-29 15:58

import itertools

from django.db import migrations


def forwards(apps, schema_editor):
    Codec = apps.get_model("entities", "Codec")
    InformationFilter = apps.get_model("entities", "InformationFilter")
    ComparisonFilter = apps.get_model("entities", "ComparisonFilter")

    av1, _created = Codec.objects.get_or_create(
        name="AV1",
        ffmpeg_args=["-c:v", "libsvtav1"],
    )
    hevc, _created = Codec.objects.get_or_create(
        name="HEVC",
        ffmpeg_args=["-c:v", "libx265"],
    )
    avc, _created = Codec.objects.get_or_create(
        name="AVC",
        ffmpeg_args=["-c:v", "libx264"],
    )

    create_video_encodings(apps, av1, hevc, avc)

    InformationFilter.objects.get_or_create(
        name="SITI",
        ffmpeg_args=["-vf", "siti=print_summary=1"],
    )

    ComparisonFilter.objects.get_or_create(
        name="PSNR",
        ffmpeg_args=["-filter_complex", "psnr"],
    )
    ComparisonFilter.objects.get_or_create(
        name="VMAF",
        ffmpeg_args=["-lavfi", "libvmaf"],
    )


def create_video_encodings(apps, av1, hevc, avc):
    VideoEncoding = apps.get_model("entities", "VideoEncoding")

    codec_settings = {
        'AV1': {
            'CODEC_OBJ': av1,
            'CRF_RANGE': (1, 63),
            'CRF_SAMPLE_COUNT': 15,
            'PRESETS': ('4', '5'),
        },
        'HEVC': {
            'CODEC_OBJ': hevc,
            'CRF_RANGE': (0, 51),
            'CRF_SAMPLE_COUNT': 15,
            'PRESETS': ('slower', 'slow'),
        },
        'AVC': {
            'CODEC_OBJ': avc,
            'CRF_RANGE': (10, 50),
            'CRF_SAMPLE_COUNT': 4,
            'PRESETS': ('slow', ),
        }
    }

    for encoder, encoder_params in codec_settings.items():
        crf_sample_count = encoder_params['CRF_SAMPLE_COUNT']
        crf_range = encoder_params['CRF_RANGE']
        crf_list = []
        lowest, highest = crf_range[0], crf_range[1]
        crf_list.append(lowest)

        step = (highest - lowest) / crf_sample_count

        for i in range(1, crf_sample_count - 1):
            crf_value = int(lowest + i * step)
            crf_list.append(min(crf_value, highest))

        crf_list.append(highest)
        crf_list = list(set(crf_list))
        crf_list.sort()

        for preset, crf in itertools.product(encoder_params['PRESETS'], crf_list):
            VideoEncoding.objects.get_or_create(
                name=f'{encoder} - preset {preset} - CRF {crf}',
                video_extension='mkv',
                codec=encoder_params['CODEC_OBJ'],
                extra_ffmpeg_args=f'-preset {preset} -crf {crf} -tune psnr'.split(' ')
            )


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
