# Generated by Django 4.2 on 2023-05-19 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterresults',
            name='compute_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='originalvideofile',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='originalvideofile',
            name='status',
            field=models.CharField(choices=[('R', 'Ready'), ('E', 'Encoding child videos'), ('M', 'Computing metrics'), ('D', 'Done'), ('F', 'Failed')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='comparisonfilterresult',
            name='reference_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_filter_results', to='entities.originalvideofile'),
        ),
    ]
