# Generated by Django 4.2 on 2023-05-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_filterresults_compute_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basevideofile',
            old_name='file_path',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='videoencoding',
            name='video_extension',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
