# Generated by Django 4.2 on 2023-07-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20230729_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonfilter',
            name='regex_for_value_extraction',
            field=models.CharField(default='.+average:([^ ]+) .+', max_length=1999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comparisonfilterresult',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
