# Generated by Django 4.2 on 2023-07-29 18:40

from django.db import migrations


def forwards(apps, schema_editor):
    ComparisonFilter = apps.get_model("entities", "ComparisonFilter")

    vmaf_regex = r'.*VMAF score: ([0-9.]+).*'
    try:
        vmaf = ComparisonFilter.objects.get(name="VMAF")
        vmaf.regex_for_value_extraction = vmaf_regex
        vmaf.save()
    except ComparisonFilter.DoesNotExist:
        _vmaf = ComparisonFilter.objects.create(
            name="VMAF",
            ffmpeg_args=["-lavfi", "libvmaf"],
            regex_for_value_extraction=r'.*VMAF score: ([0-9.]+).*',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_comparisonfilter_regex_for_value_extraction_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
