# Generated by Django 4.2 on 2023-08-20 14:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_auto_20230729_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseGraph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, default='', validators=[django.core.validators.RegexValidator(regex='^(.+)\\.html')])),
                ('original_video_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.originalvideofile')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EncodingTimeGraph',
            fields=[
                ('basegraph_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.basegraph')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=('entities.basegraph',),
        ),
        migrations.CreateModel(
            name='MetricGraph',
            fields=[
                ('basegraph_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.basegraph')),
                ('video_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.comparisonfilter')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=('entities.basegraph',),
        ),
    ]
