# Generated by Django 4.2 on 2023-08-20 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_basegraph_encodingtimegraph_metricgraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='BDMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('bd_rate', models.FloatField()),
                ('bd_metric', models.FloatField()),
                ('original_video_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.originalvideofile')),
                ('reference_codec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_metrics', to='entities.codec')),
                ('test_codec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_metrics', to='entities.codec')),
                ('video_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.comparisonfilter')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
