# Generated by Django 4.2 on 2023-08-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_bdmetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdmetric',
            name='original_video_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bd_metrics', to='entities.originalvideofile'),
        ),
    ]
