# Generated by Django 4.2 on 2023-10-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_comparisonfilter_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdmetric',
            name='bd_metric',
            field=models.FloatField(help_text='Average changes in the specified quality metric for the test encoder, compared to the reference encoder.'),
        ),
        migrations.AlterField(
            model_name='bdmetric',
            name='bd_rate',
            field=models.FloatField(help_text='Average changes in bitrate for the test encoder, compared to the reference encoder (expressed as a percentage).'),
        ),
    ]
