# Generated by Django 4.2 on 2023-10-08 17:12

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_comparisonfilter_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decodedvideofile',
            name='ffprobe_info',
            field=django_jsonform.models.fields.JSONField(blank=True, help_text='Video metadata extracted with ffprobe.', null=True),
        ),
        migrations.AlterField(
            model_name='encodedvideofile',
            name='ffprobe_info',
            field=django_jsonform.models.fields.JSONField(blank=True, help_text='Video metadata extracted with ffprobe.', null=True),
        ),
        migrations.AlterField(
            model_name='originalvideofile',
            name='ffprobe_info',
            field=django_jsonform.models.fields.JSONField(blank=True, help_text='Video metadata extracted with ffprobe.', null=True),
        ),
    ]
