# Generated by Django 4.2 on 2023-10-08 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_alter_decodedvideofile_ffprobe_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bdmetric',
            old_name='video_filter',
            new_name='comparison_filter',
        ),
        migrations.RenameField(
            model_name='comparisonfilterresult',
            old_name='video_filter',
            new_name='comparison_filter',
        ),
        migrations.RenameField(
            model_name='informationfilterresult',
            old_name='video_filter',
            new_name='information_filter',
        ),
        migrations.RenameField(
            model_name='metricgraph',
            old_name='video_filter',
            new_name='comparison_filter',
        ),
    ]
