# Generated by Django 4.2 on 2023-10-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_rename_video_filter_bdmetric_comparison_filter_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoEncoding',
            new_name='EncoderSetting',
        ),
        migrations.RenameField(
            model_name='encodedvideofile',
            old_name='video_encoding',
            new_name='encoder_setting',
        ),
        migrations.AlterUniqueTogether(
            name='encodedvideofile',
            unique_together={('original_video_file', 'encoder_setting')},
        ),
    ]
