# Generated by Django 4.2 on 2023-10-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_rename_videoencoding_encodersetting_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Codec',
            new_name='Encoder',
        ),
        migrations.RenameField(
            model_name='bdmetric',
            old_name='reference_codec',
            new_name='reference_encoder',
        ),
        migrations.RenameField(
            model_name='bdmetric',
            old_name='test_codec',
            new_name='test_encoder',
        ),
        migrations.RenameField(
            model_name='encodersetting',
            old_name='codec',
            new_name='encoder',
        ),
    ]
