default_stages:
  - commit
  - push

default_language_version:
  python: python3.11

exclude: |
  (?x)(
    ^.*/migrations/|
    ^.*/static/|
    ^.*/staticfiles/
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-ast

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [
          "--py311-plus",
        ]
        language: python

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.2
    hooks:
      - id: autoflake
        args: [
          "--in-place",
          "--recursive",
          "--remove-all-unused-imports",
          "--ignore-init-module-imports",
        ]
        language: python

  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args: [
          "--profile", "black",
          "--lines-between-types=1",
          "--lines-before-imports=0",
          "--lines-after-imports=2",
          "--src-path=app",
          "--src-path=app/video_coding",
          "--src-path=app/tests",
        ]
        language: python

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language: python

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language: python

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        exclude: ^tests/
        args: [
          "-lll",
        ]
        language: python
