name: CI

on:
  push:
    branches:
      - "**"

env:
  CODE_CHECKS_IMAGE_TAG: code_checks:latest
  TEST_IMAGE_TAG: tests:latest

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build code checks image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          file: Dockerfile_precommit
          tags: ${{ env.CODE_CHECKS_IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run pre-commit hooks
        run: ./scripts/run_code_checks.sh --show-diff-on-failure
        shell: bash

      - name: Build tests image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          file: ./app/Dockerfile
          tags: ${{ env.TESTS_IMAGE_TAG }}
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        run: docker compose run --rm test pytest tests/
        shell: bash
